
<header>
    <button id="btn-bars" type ="button"><i class="fa fa-bars menu-anchor"></i></button>
</header>

<menu>
    <div class="id-profile">
        <div>
            <ul>
                <li><a href="#"></a></li>
                <li><a href="#"></a></li>
                <li><a href="#"></a></li>
                <li><a href="#" id="menuOperador">Operador</a></li>
                <li><a href="#"></a></li>
                <li><a href="#"></a></li>
                <li><a href="#" id="logOut" >Sair </a> </li>
            </ul>
        </div>
</menu>
<div class="main">

    <div id="central-content">


    </div>
</div>
